Repository oats-center/isoblue, pull requests merged in 2020-10, with the labels that each got.

#85 Container-maintainer ping and pull hardening
  ansible/avena/roles/docker/files/container-maintainer.py
Labels: bug

#86 Updates to Github Actions for release
  .github/dependabot.yml
  .github/workflows/main.yml
Labels: enhancement

#93 container-maintainer pulls even if there are issues getting new docker-compose file
  ansible/avena/roles/docker/files/container-maintainer.py
Labels: bug

#84 Socketcand based CAN logger.
  .github/workflows/main.yml
  ansible/avena/roles/can/files/systemd/can@.service
  ansible/avena/roles/can/tasks/main.yml
  ansible/avena/roles/can/templates/config/can.j2
  services/can_logger/Dockerfile
  services/can_logger/can_logger.py
  services/can_logger/docker-compose.yml
  services/can_logger/requirements.txt
  services/cell_logger/cell_logger.py
  services/socketcand/Dockerfile
  services/socketcand/docker-compose.yml
  services/socketcand/socketcand.sh
Labels: enhancement

#77 CSV/DB selection for cell logger.
  services/cell_logger/cell_logger.py
Labels: enhancement

#82 Create MIT License
  LICENSE
Labels: discussion, enhancement

#99 GPS2TSDB Health Check
  services/gps2tsdb/Dockerfile
  services/gps2tsdb/healthcheck.py
Labels: enhancement
