Repository oats-center/isoblue, pull requests merged in 2021-01, with the labels that each got.

#103 Cell and can logger health checks
  services/.env
  services/can_logger/Dockerfile
  services/can_logger/can_logger.py
  services/can_logger/docker-compose.yml
  services/can_logger/healthcheck.py
  services/can_watchdog/docker-compose.yml
  services/cell_logger/Dockerfile
  services/cell_logger/docker-compose.yml
  services/cell_logger/healthcheck.py
  services/gps2tsdb/docker-compose.yml
  services/gps2tsdb/healthcheck.py
  services/oada_upload/docker-compose.yml
  services/postgres/docker-compose.yml
Labels: enhancement

#110 Upgrade OADA Helper Packages
  services/oada_upload/package.json
  services/oada_upload/yarn.lock
Labels: bug, dependencies

#111 OADA dependencies upgrade again
  services/oada_upload/package.json
  services/oada_upload/yarn.lock
Labels: dependencies

#104 CAN interface configuration in Ansible
  ansible/avena/roles/can/files/systemd/can@.service
  ansible/avena/roles/can/tasks/can.yml
  ansible/avena/roles/can/tasks/main.yml
  ansible/avena/roles/can/templates/config/can.j2
Labels: ansible, bug
